.github/workflows/ci.yml, .rubocop.yml, Gemfile, Gemfile.lock, spec/rspec/abq_spec.rb
=> add rubocop

lib/rspec/abq.rb, lib/rspec/abq/extensions.rb, spec/features/manifest_spec.rb, spec/rspec/abq_spec.rb
cleans up existing tests and gets ready for trivial abq integration (#7)
=> more testing!

.github/workflows/ci.yml, flake.nix
=> nix format

.github/workflows/ci.yml, .github/workflows/pages.yml, Gemfile, Gemfile.lock, bin/check_yard, lib/rspec/abq.rb, lib/rspec/abq/extensions.rb, lib/rspec/abq/manifest.rb, lib/rspec/abq/ordering.rb, lib/rspec/abq/version.rb, rspec-abq.gemspec
deploys documentation to https://rwx-research.github.io/rspec-abq/
=> documentation checks in CI, documentation deployed to pages

rspec-abq.gemspec
should decide on a license but we haven't yet
=> this package doesn't have a license yet

release_gem.rb
small improvements to the gem release script
=> more release tweaks

LICENSE.md, rspec-abq.gemspec
=> specify mit license in gemspec and replace license.txt with license.md

rspec-abq.gemspec
see  https://guides.rubygems.org/mfa-requirement-opt-in/
=> enforce mfa on gem push

LICENSE.md
=> fix company name in license

.rubocop.yml, Gemfile, Gemfile.lock, lib/rspec/abq.rb, release_gem.rb, spec/features/load_order_spec.rb, spec/features/manifest_spec.rb, spec/rspec/abq_spec.rb
~~# ❌ do not merge this ❌ ~~
blocked on
~~- https://github.com/rwx-research/abq/pull/186 being merged~~
~~- https://github.com/rwx-research/abq/issues/214 being resolved~~
when those changes are deployed, re-run CI and it should be green!
=> updates for newest version of abq

bin/release_gem.rb
- fix release gem script
- Bump rspec-abq to 0.2.1
=> prepare release v0.2.1

lib/rspec/abq.rb, spec/rspec/abq_spec.rb
~~blocked on https://github.com/rwx-research/abq/issues/223 being resovled~~
=> newer/current versions of abq should set fast_exit

.github/workflows/ci.yml
https://github.com/rwx-research/setup-abq/pull/6
=> Rename abq-token to access-token

Gemfile.lock, gemfiles/rspec-3.10.gemfile.lock, gemfiles/rspec-3.11.gemfile.lock, gemfiles/rspec-3.12.gemfile.lock, gemfiles/rspec-3.5.gemfile.lock, gemfiles/rspec-3.6.gemfile.lock, gemfiles/rspec-3.7.gemfile.lock, gemfiles/rspec-3.8.gemfile.lock, gemfiles/rspec-3.9.gemfile.lock, lib/rspec/abq/version.rb
incorporates @ayazhafiz's latest change (#40)
=> prepare release v1.0.1

.github/workflows/ci.yml, bin/test-worker-output.rb, lib/rspec/abq.rb, lib/rspec/abq/extensions.rb
- worker fails
- summarize worker success
=> worker can fail

.github/workflows/ci.yml, spec/features/integration_spec.rb
=> use captain cli

lib/rspec/abq.rb, spec/features/manifest_spec.rb
=> add language version to reporting

README.md
=> remind users to load the gem in the readme

README.md
what it says on the tin.
@dan-manges how does this look?
=> more targetd guidance towards when to require rspec/abq

Gemfile.lock, gemfiles/rspec-3.10.gemfile.lock, gemfiles/rspec-3.11.gemfile.lock, gemfiles/rspec-3.12.gemfile.lock, gemfiles/rspec-3.5.gemfile.lock, gemfiles/rspec-3.6.gemfile.lock, gemfiles/rspec-3.7.gemfile.lock, gemfiles/rspec-3.8.gemfile.lock, gemfiles/rspec-3.9.gemfile.lock, lib/rspec/abq/version.rb
mostly testing improvements but one major change to how we generate the manifest
=> prepare release v1.0.3

lib/rspec/abq.rb, lib/rspec/abq/extensions.rb, spec/features/__snapshots__/test_results_failing_specs-rspec-3.10.gemfile.snap, spec/features/__snapshots__/test_results_failing_specs-rspec-3.11.gemfile.snap, spec/features/__snapshots__/test_results_failing_specs-rspec-3.12.gemfile.snap, spec/features/__snapshots__/test_results_failing_specs-rspec-3.5.gemfile.snap, spec/features/__snapshots__/test_results_failing_specs-rspec-3.6.gemfile.snap, spec/features/__snapshots__/test_results_failing_specs-rspec-3.7.gemfile.snap, spec/features/__snapshots__/test_results_failing_specs-rspec-3.8.gemfile.snap, spec/features/__snapshots__/test_results_failing_specs-rspec-3.9.gemfile.snap, spec/features/__snapshots__/test_results_raising_specs-rspec-3.10.gemfile.snap, spec/features/__snapshots__/test_results_raising_specs-rspec-3.11.gemfile.snap, spec/features/__snapshots__/test_results_raising_specs-rspec-3.12.gemfile.snap, spec/features/__snapshots__/test_results_raising_specs-rspec-3.5.gemfile.snap, spec/features/__snapshots__/test_results_raising_specs-rspec-3.6.gemfile.snap, spec/features/__snapshots__/test_results_raising_specs-rspec-3.7.gemfile.snap, spec/features/__snapshots__/test_results_raising_specs-rspec-3.8.gemfile.snap, spec/features/__snapshots__/test_results_raising_specs-rspec-3.9.gemfile.snap, spec/features/test_result_spec.rb
adding some documentation as I'm implementing playwright to ensure I know what's happening
=> write some docs -- mostly to ensure I understand what's going on!

Gemfile, Gemfile.lock, gemfiles/rspec-3.11.gemfile, gemfiles/rspec-3.11.gemfile.lock, gemfiles/rspec-3.12.gemfile, gemfiles/rspec-3.12.gemfile.lock, gemfiles/rspec-3.5.gemfile, gemfiles/rspec-3.5.gemfile.lock, gemfiles/rspec-3.6.gemfile, gemfiles/rspec-3.6.gemfile.lock, gemfiles/rspec-3.7.gemfile, gemfiles/rspec-3.7.gemfile.lock, gemfiles/rspec-3.8.gemfile, gemfiles/rspec-3.8.gemfile.lock, gemfiles/rspec-3.9.gemfile, gemfiles/rspec-3.9.gemfile.lock, rspec-abq.gemspec, spec/features/integration_spec.rb
just pealing off cleanups from #80
=> small cleanups

.github/workflows/ci.yml
coverage report is available at coverage
=> upload coverage reports

.github/actionlint-matcher.json, .github/workflows/ci.yml
lints github workflows in CI and then fixes a deprecation warning to make github actions quieter / the linter happy
=> lint github workflow
